### ISSUE TITLE
Pitch and Proposal Status

### ISSUE THREAD

**Issue by milseman** [apple/swift-experimental-string-processing#107]
## Regex type and overview

- *TODO*: Draft/PR/Thread

Presents basic Regex type and gives an overview of how everything fits into the overall story 

*TODO*: Should we pull more into this topic, perhaps either typed captures or more run-time creation aspects?

## Run-time Regex construction

- Pitch thread: [Regex Syntax](https://forums.swift.org/t/pitch-regex-syntax/55711)
    + Brief: Syntactic superset of PCRE2, Oniguruma, ICU, UTS\#18, etc.
- *TODO*: Pull in discussion of initializers, extended syntaxes, and `AnyRegexOutput` into this thread

Covers the "interior" syntax, extended syntaxes, run-time construction of a regex from a string, and details of `AnyRegexOutput`.

## Regex literals

- *TODO*: Thread
- Draft: [delimiters](https://github.com/apple/swift-experimental-string-processing/pull/187)
- (Old) original pitch:
    + [Thread](https://forums.swift.org/t/pitch-regular-expression-literals/52820)
    + [Update](https://forums.swift.org/t/pitch-regular-expression-literals/52820/90)

Covers the choice of regex delimiter and integration into the Swift programming language.

*TODO*: Should we pull more into this topic? E.g. introducing typed captures here?

## Regex builder DSL

- [Pitch thread](https://forums.swift.org/t/pitch-regex-builder-dsl/56007)

Covers the result builder approach and basic API.

## String processing algorithms

- [Pitch thread](https://forums.swift.org/t/pitch-regex-powered-string-processing-algorithms/55969)

Proposes a slew of Regex-powered algorithms.

Introduces `CustomMatchingRegexComponent`, which is a monadic-parser style interface for external parsers to be used as components of a regex.

## Unicode for String Processing

*TODO*: Where is this at @natecook1000?

*[Thread on Swift Forums](https://forums.swift.org/t/pitch-character-classes-for-string-processing/52920)*

Covers three topics:

- Proposes literal and DSL API for library-defined character classes, Unicode scripts and properties, and custom character classes.
- Proposes literal and DSL API for options that affect matching behavior.
- Defines how Unicode scalar-based classes are extended to grapheme clusters in the different semantic and other matching modes.

*TODO:* 

- Pitch API for character classes/scripts/etc. (by 2/25)
- Pitch option API (by 2/25)
- Verify grapheme-break semantics (by 2/28)

*Target date:* Proposal ready for review by 3/7

## ⏳ SE-0348: `buildPartialBlock` for result builders

- [Pitch](https://forums.swift.org/t/pitch-buildpartialblock-for-result-builders/55561)
- [Proposal review](https://forums.swift.org/t/se-0348-buildpartialblock-for-result-builders/56143)

## (Old) Overview

- [Thread](https://forums.swift.org/t/declarative-string-processing-overview/52459)

Introduces our general approach: regex literals and result builders together.

## (Old) Pitch: Regular expression literals

- [Thread](https://forums.swift.org/t/pitch-regular-expression-literals/52820)
- [Update](https://forums.swift.org/t/pitch-regular-expression-literals/52820/90)

## (Old) Pitch: Strongly typed regex captures

- [Thread](https://forums.swift.org/t/pitch-strongly-typed-regex-captures/53391)

Presents the basic result builder approach of putting type arity and kind of capture in generic type parameter position.

The pitch proposes that the whole match ("capture 0") also be a generic parameter, pending a deeper look into details concerning variadic generics and/or additional result builder API.

*TODO*: Probably makes sense to slurp this up into one of the other pitches.

**Comment by milseman** [comment]
Added some brief TODOs to help clarify the next tasks for each one

**Comment by itingliu** [comment]
Algorithms pitch draft is here: https://github.com/apple/swift-experimental-string-processing/pull/188

**Comment by milseman** [comment]
This has been subsumed by a doc in the repo: https://github.com/apple/swift-experimental-string-processing/blob/main/Documentation/Evolution/ProposalOverview.md
