### ISSUE TITLE
Require unique names for named captures

### ISSUE THREAD

**Issue by rxwei** [apple/swift-experimental-string-processing#264]
According to regex101, PCRE2 requires a unique name for each capture, but the current implementation of `Regex.init(compiling:)` doesn't throw an error when there's duplicate names.

**Comment by benlings** [comment]
A slight relaxation of requiring unique names for captures would be to only allow a name to correspond to a single capture index. 

This would be following the advice given [here](https://www.regular-expressions.info/named.html#duplicate), and would be consistent with how captures are available in Tuple outputs. 

> In Perl 5.10, PCRE 8.00, PHP 5.2.14, and Boost 1.42 (or later versions of these) it is best to use a [branch reset group](https://www.regular-expressions.info/branchreset.html) when you want groups in different alternatives to have the same name, as in (?|a(?<digit>[0-5])|b(?<digit>[4-7]))c\k<digit>. With this special syntax—group opened with (?| instead of (?:—the two groups named “digit” really are one and the same group. Then backreferences to that group are always handled correctly and consistently between these flavors.

**Comment by milseman** [comment]
> A slight relaxation of requiring unique names for captures would be to only allow a name to correspond to a single capture index.
> 
> This would be following the advice given [here](https://www.regular-expressions.info/named.html#duplicate), and would be consistent with how captures are available in Tuple outputs.
> 
> > In Perl 5.10, PCRE 8.00, PHP 5.2.14, and Boost 1.42 (or later versions of these) it is best to use a [branch reset group](https://www.regular-expressions.info/branchreset.html) when you want groups in different alternatives to have the same name, as in (?|a(?[0-5])|b(?[4-7]))c\k. With this special syntax—group opened with (?| instead of (?:—the two groups named “digit” really are one and the same group. Then backreferences to that group are always handled correctly and consistently between these flavors.

@hamishknight are we tracking branch reset groups anywhere? I believe we were parsing them but I don't know if we implemented renumbering logic or not.

**Comment by hamishknight** [comment]
They're in https://github.com/apple/swift-experimental-string-processing/issues/370
