### ISSUE TITLE
`split` methods should have `maxSplits` and `omittingEmptySubsequences`

### ISSUE THREAD

**Issue by itingliu** [apple/swift-experimental-string-processing#308]
`split` methods should have `maxSplits` and `omittingEmptySubsequences` configurations to match their stdlib `String` counterpart:

```swift
split(separator:maxSplits:omittingEmptySubsequences:)
split(maxSplits:omittingEmptySubsequences:whereSeparator:)
```
https://developer.apple.com/documentation/swift/string/2894564-split

**Comment by milseman** [comment]
Was this done?

**Comment by itingliu** [comment]
Yes it's done.
