### ISSUE TITLE
Reject quantifiers on zero-width assertions

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-experimental-string-processing#312]
A repeated assertion, like `\b+` causes an infinite loop, since it checks the same position over and over without advancing in the input. We should reject regexes with this pattern and prevent `RegexBuilder` regexes from creating them.

**Comment by milseman** [comment]
Status?

**Comment by natecook1000** [comment]
Still to-do. Do you have ideas about how to handle this on the builder side? We don't have a way to prevent this in the type system — what kind of warning / error can we raise during compilation?

**Comment by hamishknight** [comment]
Ah this should probably remain open for the `RegexBuilder` part?

**Comment by hamishknight** [comment]
It does fail compilation at run time, yes. I wasn't sure whether it was worth leaving this issue open to track more improvements in that area, but sounds like it would be a more general thing.
