### ISSUE TITLE
`Regex` is only available in macOS 9999 or newer

### ISSUE THREAD

**Issue by christopherweems** [apple/swift-experimental-string-processing#340]
```
To try out the functionality provided here, download the latest open source development toolchain. Import _StringProcessing in your source file to get access to the API and specify -Xfrontend -enable-experimental-string-processing to get access to the literals.
```

Following these steps from the README doesn't seem to be all that is necessary to try out the Regex features with the `swift-DEVELOPMENT-SNAPSHOT-2022-04-21-a-osx` toolchain.

**Comment by christopherweems** [comment]
I've found a workable solution to my problem. If you know you're developing a package that will only support platforms that include the string processing APIs, you can disable availibility checking for now by adding the setting `.unsafeFlags(["-Xfrontend", "-disable-availability-checking"])` to your package manifest.

**Comment by milseman** [comment]
@rxwei is this the suggested workaround, and if so should we update the README?
