### ISSUE TITLE
Inconsistance throwing behavior on String and Regex's xxMatch

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-experimental-string-processing#516]
https://forums.swift.org/t/inconsistance-throwing-behavior-on-string-and-regexs-xxmatch/58535

We have `public func wholeMatch(in s: String) throws -> Regex<Output>.Match?` method on `Regex` and `public func wholeMatch<R>(of r: R) -> Regex<R.RegexOutput>.Match? where R : RegexComponent` on `String`.

Their usage is something like the following and IMO they can exchange in some extend.
```swift
let regex = /Hello/
let input = "Hello world"

try regex.wholeMatch(in: input)
input.wholeMatch(of: regex) // The result is the same as the above
```

So my question is why one is marked as "throw" and the other is not. Should the throwing behavior be aligned?

Apologies if I missed something already discussed before.

**Comment by milseman** [comment]
https://forums.swift.org/t/inconsistance-throwing-behavior-on-string-and-regexs-xxmatch/58535/2
