### ISSUE TITLE
`(a*)*` spins the matching engine forever

### ISSUE THREAD

**Issue by hamishknight** [apple/swift-experimental-string-processing#542]
Attempting to match the input `"a"` against the pattern `(a*)*` appears to spin the matching engine forever.

rdar://96461197

**Comment by hamishknight** [comment]
cc @milseman

**Comment by milseman** [comment]
This is a common/natural fall out of simple backtracking. We'll want to eventually have loop analysis over an IR to avoid it, but there might be a shorter term fix we can do.
