### ISSUE TITLE
This repo has no snapshot tags or versioning so it is checked out at random commits

### ISSUE THREAD

**Issue by buttaface** [apple/swift-experimental-string-processing#566]
Now that it is enabled by default with apple/swift#42611, it is past time it either had trunk snapshot tags or was checked out at some set version, [rather than whatever the latest commit on the swift/main branch happens to be](https://github.com/apple/swift/blob/main/utils/update_checkout/update-checkout-config.json#L125).

**Comment by buttaface** [comment]
@shahmishal, I don't know if you need to set this up, or if the repo maintainers can.

**Comment by buttaface** [comment]
@rxwei, you added this branch to the main repo in apple/swift#41588, let me know what you think.

**Comment by rxwei** [comment]
It's actually intentional that a developer needs to pull swift/main to build it with swift's main branch, which is exactly how it works with swift-driver and swift-tools-support-core.

**Comment by buttaface** [comment]
That's fine for casual development, but both [swift-driver](https://github.com/apple/swift-driver/tags) and [swift-tools-support-core](https://github.com/apple/swift-tools-support-core/tags) provide snapshot tags, so that anyone building trunk or the 5.7 branch can check out those repos at a verified tag. Otherwise, you're stuck in a situation like with this repo, where if there are recent commits to swift/main, different devs are going to end up checking out different commits and potentially getting different results.

**Comment by rxwei** [comment]
Ok I see what you mean. I think the snapshot tags should be set up. @shahmishal

**Comment by buttaface** [comment]
Ping again, I'd like to build this repo as part of my daily Android CI, which downloads the latest Swift source snapshots and cross-compiles them for Android, but that requires more work to automate as long as this repo has no automated tags.

**Comment by buttaface** [comment]
@rxwei, I see no commits to the swift/main branch in the last two months: maybe you can tag that last commit as a release and use it instead in the update-checkout script? Even if you don't change how that toolchain script checks this repo out, simply providing a tag will make it easier for downstream users like me to check it out.

**Comment by rxwei** [comment]
@stephentyrone @shahmishal

**Comment by buttaface** [comment]
Pinging @shahmishal again: it's been 7 months since this was added to the toolchain, it really should be tagged by version for trunk/5.8 or at least provide snapshot tags by now. [I use the currently providef 5.7 release tags for my Android CI](https://github.com/buttaface/swift-android-sdk/blob/2e27dee78067985c634755f32d9b0ac1f0d44b18/get-packages-and-swift-source.swift#L51).

**Comment by shahmishal** [comment]
Sorry for the delay, this issue is resolved as of Jan 14 nightly toolchain.

**Comment by buttaface** [comment]
Thanks, looking forward to using it.
