### ISSUE TITLE
`[\n]` should not match `\r\n`

### ISSUE THREAD

**Issue by hamishknight** [apple/swift-experimental-string-processing#568]
Currently `[\n]` matches `\r\n` in grapheme semantic mode, however this should not be the case.

**Comment by milseman** [comment]
This is open for debate as to whether we consider `\n` to be a literal scalar escape or some kind of newline character class.

**Comment by hamishknight** [comment]
@milseman AFAIK other engines treat `[\n]` as equivalent to `\n`. We could define it differently, though that would also mean we'd also have to ban its use as a range operand e.g `[\n-0]`

**Comment by hamishknight** [comment]
Happy to re-open if we decide we want a custom matching behavior instead
