### ISSUE TITLE
Add builtin character class atoms to the DSL tree

### ISSUE THREAD

**Issue by hamishknight** [apple/swift-experimental-string-processing#579]
For the following escape builtins:

- `graphemeCluster`
- `whitespace`
- `decimalDigit`
- `horizontalWhitespace`
- `newlineSequence`
- `verticalTab`
- `wordCharacter`

We currently form DSL character classes using their unconverted AST atoms. We ought to have DSL representations for them, perhaps under an e.g `BuiltinCharacterClass`  type.

**Comment by hamishknight** [comment]
This could also be done alongside migrating them off consumers and onto dedicated instructions in byte code gen

**Comment by hamishknight** [comment]
Lily has a PR for this

**Comment by rctcwyvrn** [comment]
Fixed in https://github.com/apple/swift-experimental-string-processing/pull/547
